### ISSUE TITLE
I get different results when running on windows or mac using the same set.seed. I tries to reconstruct a longitudinal data, but I notices my results are very different when using different computers. 

### ISSUE THREAD

**Issue by soroushmdg** [functionaldata/tPACE#62] opened 2023-12-13 14:11 UTC
If you are filing an enhancement/feature request, make sure you:

- Provide at least one reference about it, or
- Provide at least one particular user case.

If you are filing a bug, make sure these steps are followed before submitting your issue - it will help us help you more efficiently!

- Start a new R session
- Make sure you are using the latest version of `fdapace` (eg. `update.packages(oldPkgs="fdapace", ask=FALSE)`)
- [Write a minimal reproducible example](http://stackoverflow.com/a/5963610)
- Run `sessionInfo()`

If you are having a general question about using `fdapace` or its design:

- Email us at first instance; we are happy to help new users of fdapace. :D

**Comment by CrossD** [comment] 2023-12-13 16:00
This is probably an intended behavior of R: https://stackoverflow.com/questions/68830176/different-set-seed-sample-function-results-with-same-versions-of-r-in-different

The issue does not seem to be related to `fdapace`. Closing.

**Closed by CrossD** 2023-12-13 16:00 UTC
